### ISSUE TITLE
Fix the dropshadow on the sidebar

### ISSUE THREAD

**Issue by nullhook** [Framaterial/framaterial#10]
The side panel has a very strong drop shadow which casts odd black shades to the components on the right. It's making the layout look wrong. The original Google Material site does not have a show at all in the side bar.

**Comment by LukyVj** [comment]
Fixed, I let this issue open for some days tho.

**Comment by LukyVj** [comment]
Well, I will add some drop shadows back, according to the new Google IO 2015 homepage, there is some subtle drop shadows : https://events.google.com/io2015/
